### ISSUE TITLE
feature request: add ignore table env variable

### ISSUE THREAD

**Issue by wilkis3** [selim13/docker-automysqlbackup#15]
Sometimes we would like to backup only chosen databases and tables.
Mysqldump supports the option [--ignore-table](https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html#option_mysqldump_ignore-table) and the current image also supports to exclude databases.

**Comment by wilkis3** [comment]
No response.

**Comment by selim13** [comment]
Sorry, I don't personally use this image very often, and have very little time to maintain it.
PR's are welcome.

I will keep this issue open.

**Comment by selim13** [comment]
This should work in 2.6-8-debian now.
