### ISSUE TITLE
Typo version mysql5.7

### ISSUE THREAD

**Issue by guillaume-gambs** [selim13/docker-automysqlbackup#17]
Hello,

After a quick review, I find a [typo on an image name](https://github.com/selim13/docker-automysqlbackup/blob/5ad6e608fb80a5d3aa093c8a7ebeac743dca45cb/docker-compose.yml#L16) the correct name is [2.6-9-mysql57](https://hub.docker.com/r/selim13/automysqlbackup/tags?page=1&name=mysql)

**Comment by selim13** [comment]
fixed, thanks!
