### ISSUE TITLE
Can the container cron wake up the host?

### ISSUE THREAD

**Issue by bradbulger** [selim13/docker-automysqlbackup#24]
If the host machine is asleep, what is the state of the container? Is it suspended, or can cron still execute at a given clock time? I would like to run this when I'm not actively using the machine but when I'm not using it, it goes to sleep. Thanks.

**Comment by selim13** [comment]
During the sleep mode, all processes of your PC will stop, including docker and it's containers. So cron will be suspended as well.

**Comment by bradbulger** [comment]
That's how I thought it worked. So I might be able to put a docker exec command in the host's own cron file, which might be able to wake it up, but nothing in the containers is going to affect that.
