### ISSUE TITLE
Add Retention Options

### ISSUE THREAD

**Issue by TPGeek** [selim13/docker-automysqlbackup#3]
In AutoMySQL backup, there is retention preferences, could you include them in this container please?

`
 Set rotation of daily backups. VALUE*24hours
 If you want to keep only today's backups, you could choose 1, 
 i.e. everything older than 24hours will be removed.
CONFIG_rotation_daily=6

 Set rotation for weekly backups. VALUE*24hours
CONFIG_rotation_weekly=35

 Set rotation for monthly backups. VALUE*24hours
CONFIG_rotation_monthly=150
`

**Comment by selim13** [comment]
As far as I can tell, those options are from AutoMySQLBackup v3.0 which was never fully released (the last one was 3.0rc6).
This container uses a fork of older v2.5 from Debian, which is much simpler and doesn't those options.

**Comment by TPGeek** [comment]
Ah, That's a shame! 
Thank you anyway 👍
