### ISSUE TITLE
selim13/automysqlbackup:2.6-3-debian doesn't do full backups

### ISSUE THREAD

**Issue by abduncan** [selim13/docker-automysqlbackup#7]
I pulled this image and ran it. I backed up the first table of the database and quit.

I pulled image selim13/automysqlbackup:2.6-4-debian and it seems to be working properly.

I only bring this up because your docker-compose example has selim13/automysqlbackup:2.6-3-debian

**Comment by selim13** [comment]
I've bumped the image version to 2.6-4-debian in docker-compose.yml.
Thanks for noticing!
